version: '2'

services:
  grafana:
    image: grafana/grafana-oss
    user: $DOCKER_UID:$DOCKER_GID
    ports:
      - 3000:3000
    volumes:
      - /data/nfe-reader/grafana/data:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=America/Sao_Paulo

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /data/nfe-reader/postgres/data:/data/pgdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/pgdata
